@echo off
setlocal enabledelayedexpansion

:: ==========================================
:: 1. GET WEBSITE INPUT FROM USER
:: ==========================================
cls
echo ===================================================
echo             NETWORK DIAGNOSTIC TOOL
echo ===================================================
echo.
set /p "TARGET_SITE=Enter the website URL or domain (e.g., example.com): "

:: Remove http:// or https:// if entered by the user
set "TARGET_DOMAIN=%TARGET_SITE:http://=%"
set "TARGET_DOMAIN=%TARGET_DOMAIN:https://=%"

:: Extract just the domain if a path was included
for /f "tokens=1 delims=/" %%a in ("!TARGET_DOMAIN!") do set "TARGET_DOMAIN=%%a"

if "%TARGET_DOMAIN%"=="" (
    echo [ERROR] No domain provided. Exiting...
    pause
    exit /b
)

:: Set Report Details
set "TIMESTAMP=%date:~-4%-%date:~4,2%-%date:~7,2%_%time:~0,2%-%time:~3,2%-%time:~6,2%"
set "TIMESTAMP=%TIMESTAMP: =0%"
set "REPORT_FILE=report_%TARGET_DOMAIN%_%TIMESTAMP%.txt"

cls
echo ===================================================
echo Running diagnostics for: %TARGET_DOMAIN%
echo Saving report to:        %REPORT_FILE%
echo ===================================================
echo Please wait, this may take a minute or two...
echo.

:: ==========================================
:: 2. GENERATE DIAGNOSTIC REPORT
:: ==========================================

echo =================================================== > "%REPORT_FILE%"
echo           SITE DIAGNOSTIC REPORT                   >> "%REPORT_FILE%"
echo =================================================== >> "%REPORT_FILE%"
echo Target Site:   %TARGET_DOMAIN%                      >> "%REPORT_FILE%"
echo Date / Time:   %date% %time%                        >> "%REPORT_FILE%"
echo Generated By:  %USERNAME% on %COMPUTERNAME%         >> "%REPORT_FILE%"
echo =================================================== >> "%REPORT_FILE%"
echo. >> "%REPORT_FILE%"

:: Test 1: DNS Resolution (nslookup)
echo [1/5] Testing DNS Resolution...
echo --- [1. DNS RESOLUTION (nslookup)] ---             >> "%REPORT_FILE%"
nslookup %TARGET_DOMAIN%                                >> "%REPORT_FILE%" 2>&1
echo. >> "%REPORT_FILE%"

:: Test 2: Ping Test (ICMP Reachability)
echo [2/5] Testing Ping Connectivity...
echo --- [2. PING TEST] ---                             >> "%REPORT_FILE%"
ping -n 4 %TARGET_DOMAIN%                               >> "%REPORT_FILE%" 2>&1
echo. >> "%REPORT_FILE%"

:: Test 3: Traceroute (Network Path)
echo [3/5] Tracing Network Route (Traceroute)...
echo --- [3. TRACEROUTE (tracert)] ---                  >> "%REPORT_FILE%"
tracert -d -h 15 %TARGET_DOMAIN%                        >> "%REPORT_FILE%" 2>&1
echo. >> "%REPORT_FILE%"

:: Test 4: HTTP/HTTPS Status Check via PowerShell
echo [4/5] Checking Web Response (HTTP/HTTPS Status)...
echo --- [4. HTTP / HTTPS STATUS CHECK] ---             >> "%REPORT_FILE%"
powershell -Command "try { $res = Invoke-WebRequest -Uri 'https://%TARGET_DOMAIN%' -Method Head -TimeoutSec 10; Write-Output 'HTTPS Status: ' $res.StatusCode $res.StatusDescription } catch { Write-Output 'HTTPS Check Failed or Timed Out:' $_.Exception.Message }" >> "%REPORT_FILE%" 2>&1
echo. >> "%REPORT_FILE%"

:: Test 5: Local Network & DNS Cache
echo [5/5] Collecting Local Network Context...
echo --- [5. LOCAL IP & DNS CONFIGURATION] ---          >> "%REPORT_FILE%"
ipconfig /displaydns | findstr /i "%TARGET_DOMAIN%"     >> "%REPORT_FILE%" 2>&1
if errorlevel 1 echo (No local DNS cache entry found for %TARGET_DOMAIN%) >> "%REPORT_FILE%"
echo. >> "%REPORT_FILE%"

:: ==========================================
:: 3. FINISH & OPEN REPORT
:: ==========================================
echo ===================================================
echo Diagnostics complete! 
echo Report saved to: %cd%\%REPORT_FILE%
echo ===================================================
echo.
set /p "OPEN_NOW=Would you like to open the report now? (Y/N): "
if /i "%OPEN_NOW%"=="Y" notepad "%REPORT_FILE%"

endlocal
